services:
  api:
    build: ./server
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: recruit_AI
      
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      LANGCHAIN_PROJECT: ${LANGCHAIN_PROJECT}
      LANGCHAIN_TRACING_V2: ${LANGCHAIN_TRACING_V2}

      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_GRPC_PORT: 6334
      QDRANT_COLLECTION: ResumeVectorBase

      DATA_PATH: /app/data

    depends_on:
      - db
      - qdrant

    volumes:
      - ./server/backend/data:/app/data

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recruit_AI
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/backend/create_database.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "8001:80"
    depends_on:
      - api

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"    
      - "6334:6334"    
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  db_data:
  qdrant_storage:
